### ISSUE TITLE
In what kind of format pcap file should be?, I tried just to tcpdump -w sniffer_data.pcap and dragged it to site, but it doesn't work.

### ISSUE THREAD

**Issue by nursultan1201b** [jsonbrazeal/pcapview#1]

**Comment by jasonbrazeal** [comment]
I just updated this project to work with a newer version of the tshark command. It's working with 2.2.6 now. The old command has less precise times, so the datetime parsing was failing in Python. Anyway, it should work with your `tcpdump -w sniffer_data.pcap` command output now.

**Comment by nurs1** [comment]
Oh, thanks very much, but now SyntaError appeared :)

$ python pcapview/pcapview.py 
  File "pcapview/pcapview.py", line 56
    p[1] = f'{seconds}.{new_microseconds}'
                                         ^
SyntaxError: invalid syntax

**Comment by jasonbrazeal** [comment]
That's probably because of the format string syntax. It's only available in
Python 3.6 and later:
https://docs.python.org/3/whatsnew/3.6.html#whatsnew36-pep498. Can you
upgrade your Python version?

**Comment by nursultan1201b** [comment]
That was my bad, i used python 2.7, for now I've upgraded my Python version and it works perfectly.
Thank you, sir very much for fast reaction and nice pcap visualizer :+1:
